### PR TITLE
Added version inside interpreter and last available version

### PR DESCRIPTION
**Pull request by mgckind**

### CODE REVIEW

**Comment by kadrlica** [comment]
Have you ever looked into [`versioneer`](https://github.com/warner/python-versioneer)? I've found it to be a nice way to keep git tags and version info up to date. Also, argparse does have a [`version`](https://docs.python.org/3/library/argparse.html#action) action that could be used.

**Comment by mgckind** [comment]
You mentioned it before, it might be an option in the future as we collect more users and have more "followers" and more frequent releases. 

And yes, I liked the action='version' we had, but wanted to be able to print out current available version as well from pypi (and conda) and didn't want to modify the Action class. we might revert this change if the latest release version is not useful.

Thanks!

**Comment by kadrlica** [comment]
Sounds good. My point was that we could package all of the version printing into a single function that returns a string and just call that as the argument of the 'version' action. 

```
parser.add_argument("-v", "--version", action = "version", version = print_version(),...
```

In the end it doesn't matter at all, so not worth spending time on.

**Comment by mgckind** [comment]
Yeah, that sounds more pythonic. I'll revisit this soon. I'm planning to do a general clean up

**Comment by kadrlica** [comment]
I'm getting this error when I try to import `easyacess` (this is without a pip install and just pointing my pythonpath to the easyaccess directory):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "easyaccess/__init__.py", line 1, in <module>
    from .easyaccess import *
  File "easyaccess/easyaccess.py", line 33, in <module>
    from version import __version__, last_pip_version
ImportError: No module named version
```

**Comment by kadrlica** [comment]
Digging deeper, I think this is related to the `version` import in `fileio.py`. Specifically here:
https://github.com/mgckind/easyaccess/blob/d227e72ba6fcda4e8b3f8a34e3f5c9fa72516843/easyaccess/eautils/fileio.py#L14

We have the added complication of trying to maintain compatibility whether or not `easyaccess` has been installed with the setup.py, so I think we need to have the `version` import in the `try... except` block.

Would it be possible to clean this up somehow? How much of the issue is related to the fact that both the module and the source file are named `easyaccess`?

**Pull request merged**
